---
apiVersion: v1
kind: Service
metadata:
  name: webdav-bardin-haus-app
  labels:
    ttl: '16'
spec:
  type: NodePort
  ports:
  - nodePort: 32212
    port: 8080
    protocol: TCP
  selector:
    name: webdav
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webdav-bardin-haus-vhost
  labels:
    ttl: '16'
spec:
  rules:
  - host: webdav.bardin.haus
    http:
      paths:
      - backend:
          serviceName: webdav-bardin-haus-app
          servicePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
  labels:
    ttl: '16'
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      name: webdav
  template:
    metadata:
      labels:
        name: webdav
        ttl: '16'
    spec:
      volumes:
      - name: run
        emptyDir: {}
      containers:
      - name: webdav-bardin-haus-app
        image: webdav.bardin.haus:latest
        imagePullPolicy: IfNotPresent
        volumeMounts: 
        - mountPath: /var/run/apache2
          name: run
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 200Mi
            cpu: 50m
          requests:
            memory: 100Mi
            cpu: 10m
        command:
        - "apache2"
        - "-D"
        - "FOREGROUND"
        env: &1
        - name: APP_ENV
          value: production
